apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- service.yaml
- service_account.yaml
- pdb.yaml

images:
- name: ghcr.io/milo-os/service-catalog
  newTag: latest

configMapGenerator:
- files:
  - config.yaml
  name: services-config
  options:
    disableNameSuffixHash: true
